### ISSUE TITLE
--experimental-java is unable to parse constants defined inline

### ISSUE THREAD

**Issue by dmontauk** [twitter/scrooge#168]
Simple Thrift file:

```
struct Foo {
  1: optional i32 bar
}

const map<string, Foo> testmap = {
  "test": {'bar' : 1}
}
```

This works with Apache Thrift:
`thrift --gen java -strict --debug -v /tmp/scrooge/test.thrift`

But fails in Scrooge:
`./sbt 'scrooge-generator/run-main com.twitter.scrooge.Main -l experimental-java test.thrift`

```
[error] (run-main-0) com.twitter.scrooge.frontend.TypeMismatchException: Expecting StructType(Struct(SimpleID(Foo,None),Foo,List(Field(1,SimpleID(bar,None),bar,TI32,None,Optional,Map(),Map())),None,Map()),None), found MapRHS(List((StringLiteral(bar),IntLiteral(1))))
com.twitter.scrooge.frontend.TypeMismatchException: Expecting StructType(Struct(SimpleID(Foo,None),Foo,List(Field(1,SimpleID(bar,None),bar,TI32,None,Optional,Map(),Map())),None,Map()),None), found MapRHS(List((StringLiteral(bar),IntLiteral(1))))
	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:213)
	at com.twitter.scrooge.frontend.TypeResolver$$anonfun$apply$5.apply(TypeResolver.scala:195)
	at com.twitter.scrooge.frontend.TypeResolver$$anonfun$apply$5.apply(TypeResolver.scala:195)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:195)
	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:140)
	at com.twitter.scrooge.frontend.TypeResolver$$anonfun$apply$2.apply(TypeResolver.scala:103)
	at com.twitter.scrooge.frontend.TypeResolver$$anonfun$apply$2.apply(TypeResolver.scala:102)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:102)
	at com.twitter.scrooge.Compiler$$anonfun$run$2.apply(Compiler.scala:72)
	at com.twitter.scrooge.Compiler$$anonfun$run$2.apply(Compiler.scala:67)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at com.twitter.scrooge.Compiler.run(Compiler.scala:67)
	at com.twitter.scrooge.Main$.main(Main.scala:30)
	at com.twitter.scrooge.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by mosesn** [comment]
experimental java was pretty broken and nobody used it so we deleted it.  we might revisit it in the future.
