### ISSUE TITLE
 com.twitter#scrooge-sbt-plugin;4.5.0: not found

### ISSUE THREAD

**Issue by drocsid** [twitter/scrooge#242]
created the same plugins.sbt and build.sbt as shown in the docs: https://twitter.github.io/scrooge/SBTPlugin.html . When I sbt ; compile I get com.twitter#scrooge-sbt-plugin;4.5.0: not found (scalaVersion=2.10, sbtVersion=0.13)

### Expected behavior

follow the docs, get deps, compile code

### Actual behavior

com.twitter#scrooge-sbt-plugin;4.5.0: not found

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

1) create the same plugins.sbt and build.sbt as shown in the docs: https://twitter.github.io/scrooge/SBTPlugin.html . 

2) sbt compile 

3) I get com.twitter#scrooge-sbt-plugin;4.5.0: not found (scalaVersion=2.10, sbtVersion=0.13)

**Comment by drocsid** [comment]
I tried adding bintray as a resolver to plugins.sbt:

resolvers += "twitter-repo" at "https://maven.twttr.com"
resolvers += "scrooge-sbt-plugin" at "https://bintray.com"

addSbtPlugin("com.twitter" % "scrooge-sbt-plugin" % "4.8.0")

But I see:

[info] Resolving com.twitter#scrooge-sbt-plugin;4.8.0 ...
[error] SERVER ERROR: Internal Server Error url=https://bintray.com/com/twitter/scrooge-sbt-plugin_2.10_0.13/4.8.0/scrooge-sbt-plugin-4.8.0.pom
[warn] 	module not found: com.twitter#scrooge-sbt-plugin;4.8.0
[warn] ==== local: tried
[warn]   /home/colin/.ivy2/local/com.twitter/scrooge-sbt-plugin/scala_2.10/sbt_0.13/4.8.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/twitter/scrooge-sbt-plugin_2.10_0.13/4.8.0/scrooge-sbt-plugin-4.8.0.pom
[warn] ==== scrooge-sbt-plugin: tried
[warn]   https://bintray.com/com/twitter/scrooge-sbt-plugin_2.10_0.13/4.8.0/scrooge-sbt-plugin-4.8.0.pom
[warn] ==== twitter-repo: tried
[warn]   https://maven.twttr.com/com/twitter/scrooge-sbt-plugin_2.10_0.13/4.8.0/scrooge-sbt-plugin-4.8.0.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#scrooge-sbt-plugin;4.8.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.twitter:scrooge-sbt-plugin:4.8.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter:scrooge-sbt-plugin:4.8.0 (scalaVersion=2.10, sbtVersion=0.13) (/home/colin/project/plugins.sbt#L4-5)
[warn] 		  +- default:thriftservice_2.10:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.twitter#scrooge-sbt-plugin;4.8.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.twitter#scrooge-sbt-plugin;4.8.0: not found
[error] Total time: 4 s, completed Aug 3, 2016 11:48:57 PM

**Comment by mosesn** [comment]
I think bintray is where sbt expects you to put your plugins, so it's probably one of the defaults.  I tried following the quickstart, and I can't reproduce your problem.  This might not be a scrooge problem.  Would love to see what you find!

**Comment by drocsid** [comment]
I tried first setting sbt.version= 0.13.11 and then sbt.version= 0.13.12 in build.properties, and either way I still get sbt.ResolveException: unresolved dependency: com.twitter#scrooge-sbt-plugin;4.8.0: not found

**Comment by drocsid** [comment]
looks like it was due to a path issue, closing.
