### ISSUE TITLE
Scrooge Generated Java Client throws java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by knightpop** [twitter/scrooge#256]
One line summary of the issue here.

### Expected behavior

I just want to call thrift service function

### Actual behavior

1. Thrift Server didn`t get request.

2. Throws exception
`java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at kk.gift.auth.thriftjava.TOrderSessionService$ServiceToClient$2$1.apply(TOrderSessionService.java:626)
	at kk.gift.auth.thriftjava.TOrderSessionService$ServiceToClient$2$1.apply(TOrderSessionService.java:621)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1089)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:1088)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:405)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
	at com.twitter.util.Promise.update(Promise.scala:775)
	at com.twitter.util.Promise.setValue(Promise.scala:751)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:120)
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:281)
	at com.twitter.finagle.netty3.codec.BufCodec.messageReceived(BufCodec.scala:26)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at com.twitter.finagle.mux.transport.Netty3Framer$Framer.handleUpstream(Netty3Framer.scala:32)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
	at java.lang.Thread.run(Thread.java:745)`

### Steps to reproduce the behavior

1. append to build.sbt
`scroogeLanguages in Compile := Seq("java", "scala")`

2. generate java class

`sbt compile`

3. make client

`ThriftMux.client().newIface(
 Name$.MODULE$.bound(convertStringToAddresses(server)),
 ClientLabel,
 TOrderSessionService.Iface.class
 )`

4. call function

5. Error Occure

**Comment by jcrossley** [comment]
Hey @knightpop, we just published scrooge for 2.12; it now compiles with 2.12 by default. Have you tried compiling your code with 2.12, or specifying 2.11 manually?

**Comment by knightpop** [comment]
@jcrossley Thanks for reply. I use 
`addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.5")`

And give option to specific compile

`  scroogeThriftDependencies in Compile := Seq(
    "finatra-thrift_2.11"
  ),`

Not the newest version.

Do i have to use newest version?

Thanks for fast reply again. and Merry christmas!!

**Comment by jcrossley** [comment]
Hey @knightpop, are you compiling *your* code with 2.12? The plugin and dependencies that you're using are for 2.11. Definitely seems like a mismatched version problem here, given the error. Have you cleaned your target directory?

**Comment by knightpop** [comment]
@jcrossley Sorry for reply late..TT

I`m using scala 2.11.8
also, I clean & also, delete all and clone again.
hm... at last... i decide to use only scala generator...

to sum up....
- enviroment : scala 2.11.8, scrooge-sbt-plugin 4.12.0, spring boot version 1.4.2.RELEASE, tomcat.version 8.0.39
- I want to use java client generated by scrooge in java server made with spring boot.
- error occur....

history
error occure
- delete my server dir (clear all)
- clone again
- compile
- use java client(generated by scrooge) -> above error occur

by the way, is java client generated by scrooge stable?
there is no document

**Comment by ryanoneill** [comment]
Hi @knightpop, the Java client generated by Scrooge should be good. 

If you haven't already, I would recommend taking a look at the [java-thrift-server example](https://github.com/twitter/finatra/tree/develop/examples/java-thrift-server) in Finatra. It uses Scrooge to [generate Java code](https://github.com/twitter/finatra/blob/develop/examples/java-thrift-server/build.sbt.for_release_branches_only#L81) and has a [Java client](https://github.com/twitter/finatra/blob/develop/examples/java-thrift-server/thrift-example-server/src/test/java/com/twitter/calculator/CalculatorServerFeatureTest.java#L24) that it uses for tests.

Moving forward, I'm a little confused by your setup as far as where you're using Scala and where you're using Java. Are you using Java for the client with Spring Boot and Scala for the server, or something different? 

Also, I'd just like to verify that this issue isn't related to the [other issue that you filed](https://github.com/twitter/finagle/issues/577).

**Comment by mosesn** [comment]
@knightpop since you haven't continued replying to this thread, I assume you fixed your problem.  If you haven't, please reopen and we can take another look.
