### ISSUE TITLE
Passing Some(null) to service methods generates NPE

### ISSUE THREAD

**Issue by scf37** [twitter/scrooge#257]
Scrooge-generated code does not handle Some(null) for optional parameters and struct fields

### Expected behavior

Some(null) on server side

### Actual behavior
```
java.lang.NullPointerException:
 at com.twitter.finagle.thrift.Protocols$TFinagleBinaryProtocol.writeString(Protocols.scala:163)
 at model.thriftscala.TestStruct$.model$thriftscala$TestStruct$$writeOsValue(TestStruct.scala:322)
 at model.thriftscala.TestStruct$.model$thriftscala$TestStruct$$writeOsField(TestStruct.scala:317)
 at model.thriftscala.TestStruct$class.write(TestStruct.scala:561)
 at model.thriftscala.TestStruct$Immutable.write(TestStruct.scala:337)
 at model.thriftscala.TestService$TestOption$Args$.model$thriftscala$TestService$TestOption$Args$$writeArgValue(TestService.scala:590)
 at model.thriftscala.TestService$TestOption$Args$.model$thriftscala$TestService$TestOption$Args$$writeArgField(TestService.scala:585)
 at model.thriftscala.TestService$TestOption$Args.write(TestService.scala:618)
 at model.thriftscala.TestService$FinagleClient.encodeRequest(TestService$FinagleClient.scala:53)
 at model.thriftscala.TestService$FinagleClient$$anonfun$testOption$1.apply(TestService$FinagleClient.scala:181)
```

### Steps to reproduce the behavior
```
struct TestStruct {
    1: i32 i
    2: string s
    3: optional string os
}

service TestService {
    string testOption(1: optional TestStruct arg)
}
```

```
val clientService = ThriftMux.client.newService(addr)
val client = new FinagledClient(clientService)
client.testOption(Some(null))
```

**Comment by kevinoliver** [comment]
I believe the expectation is that you'll use `None` instead of `Some(null)`.

**Comment by ryanoneill** [comment]
While `Some(null)` is valid Scala and there are [legitimate reasons](http://stackoverflow.com/questions/5796616/why-somenull-isnt-considered-none) for it in the language, I don't know that it makes sense for us to handle it differently than we do within the context of Scrooge.

**Comment by mosesn** [comment]
@scf37 based on previous discussion, I don't think we're going to change this behavior, so I'm going to close this ticket.  Please reopen if you want to continue discussing it.
