### ISSUE TITLE
Scrooge fails generation when exception definition is added to the IDL file

### ISSUE THREAD

**Issue by tencentflo** [twitter/scrooge#278]
I have a simple finagle thrift server which has been working just fine but when I add an exception to the IDL, scrooge fails to compile

```
com.twitter.scrooge.frontend.FileParseException: Exception parsing: tensorflow-service/src/main/thrift/tensorflowservice.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: tensorflow-service/src/main/thrift/tensorflowservice.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.ParseException: [8.34] failure: `(' expected but `{' found
  exception TestServiceException {
                                 ^
	at com.twitter.util.NoStacktrace(Unknown Source)

```

The IDL is

```
namespace java com.me.tensorflowservice.thriftjava
#@namespace scala com.me.tensorflowservice.thriftscala

namespace rb TensorflowService

service TensorflowService {

  exception TestServiceException {
    1: string description
  }

  i32 classify(
    1: binary imageData
  )

  i32 addNumbers(
    1: i32 a
    2: i32 b
  )
}
```

I looked at several examples and and the syntax for exception is correct as far as I can tell. To generate the thrift-scala I'm running

sbt scrooge-gen

This project is very minimal at the moment, with just the recommended config I found on github:

build.sbt 

```
scalaVersion := "2.11.8"

// Exclusion rule required to evict the com.twitter libthrift library.
libraryDependencies ++= Seq(
  "org.apache.thrift" % "libthrift" % "0.9.2",
  "com.twitter" %% "scrooge-core" % "4.6.0" exclude("com.twitter", "libthrift"),
  "com.twitter" %% "finagle-thrift" % "6.34.0" exclude("com.twitter", "libthrift")
)

libraryDependencies += "ch.qos.logback"    %  "logback-classic" % "1.1.3"
libraryDependencies += "org.rogach" %% "scallop" % "3.1.0"

```

plugins.sbt

```
resolvers += Classpaths.typesafeReleases

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0")
addSbtPlugin("com.twitter" % "scrooge-sbt-plugin" % "4.5.0")
```

sbt version 0.13.16

**Comment by bryce-anderson** [comment]
Are you sure you should be defining the exception within the service definition?

**Comment by tencentflo** [comment]
Apparently not. Thanks
