### ISSUE TITLE
Parse failure. 

### ISSUE THREAD

**Issue by yehbrianyeh** [twitter/scrooge#307]
One line summary of the issue here.

### Expected behavior

Parser should not hit an exception

### Actual behavior

Parser hits exception 

### Steps to reproduce the behavior

for this thrift code:
```
/**
NOHTML
<link href="wi.css" rel="stylesheet" type="text/css"/>
Copyright 2019 Parsable, Inc
<div class='apiaddress'>API address: <code>/api/abac</code></div>
<div class='content'>
 Functionality for Attribute Based Access Control.
 <br/><br/>
</div>
*/

namespace java com.wi.director.thrift.v1.abac
namespace js parsable.thrift.v1.Abac
namespace rb parsable.thrift.v1.abac
namespace cocoa TAbac

include "common.thrift"

/**
 *
 * outer map keys lists of AbacAttributes to team ids
 *
 */
typedef map<string, list<AbacAttribute> > TeamScopedAbacAttributes 

enum AbacActorType {
  USER = 0,
  TEAM = 1,
  JOB = 2,
  JOB_TEMPLATE = 3,
  TEMPLATE_SET = 4,
  ISSUE = 5,
  DATASHEET = 6,
  POLICY = 7,
  POLICY_SET = 8,
  WORKFLOW = 9,
  ANALYTICS = 10,
  TEAM_SETTINGS = 11,
  INTEGRATION_TEMPLATE = 12,
  METADATA = 13,
  METADATA_VALUE = 14,
}

struct AbacActor {
  1: string id,
  2: optional i32 version,
  3: AbacActorType type,
}

/** All actions available through the parsable api */
enum AbacAction {
  VIEW        = 0,
  CREATE      = 1,
  EDIT        = 2,
  EXECUTE     = 3,
  PUBLISH 	  = 4,
  COLLABORATE = 5,
  ARCHIVE     = 6, 
}

/** Attribute Value Update Behaviour  */
enum AbacUploadBehaviour {
  CLOBBER = 0,  /** clobber all existing values with new values */
  MERGE   = 1,  /** merge existing values with new values */
}

/**
 * The value of a parsable ABAC attribute
 */
struct AbacAttributeValue {
  1: string id,
  2: string label,
  /* 3: AbacContext context */
}

/**
 * Transport for ABAC attribute definitions
 */
struct AbacAttribute {
  1: string id,
  2: string label, 								/** ui label for this attribute */
  3: list<AbacAttributeValue> values, 	/** the allowed values for this attribute, keys are unique within Attribute scope */
  /** 4: AbacContext context */					/** future scope */
}

/**
  <object> <subject> <action> represents an authorization resolution request.
  Can <object> perform <action> on <subject>
*/
struct AbacResolutionRequest {
  1: AbacActor object,  /** the actor requesting authorization for <action> on <subject> */
  2: AbacActor subject, /** the actor being acted upon by <subject> */
  3: AbacAction action, /** the action being authorized: edit, view, archive, etc  */
  4: string teamId,     /** the team context that this request is being made within */
}

/**
  Result of an individual ABAC resolution request
  We send back the object, subject and action to the client to support batch processing
*/
struct AbacResolution {
  1: AbacActor object,  /** the actor requesting authorization for <action> on <subject> */
  2: AbacActor subject, /** the actor being acted upon by <subject> */
  3: AbacAction action, /** the action being authorized: edit, view, archive, etc  */
  4: string teamId,     /** the team context that this request is being made within */
  5: bool authorized,   /** result of the policy resolution  */
}

/**
 * An ABAC Policy
 */
struct AbacPolicy {
  1: string id, /** backend assigned unique id, if omitted, o*/
  2: string label, /** human readable label for policy */
  3: string description, /** human readable description of policy effect */
  4: string policy, /** currently expects json string */
  5: string teamId, /** */
}

/*
 *
 */
struct AbacUpdateAttributeResult {
  1: list<AbacAttribute> attributes,
  2: optional AbacActor actor,
  3: optional common.SystemException err,
}

service AbacService {
  /**
   * resolve a list of policy requests
   */
  map<string, bool> resolve(1: map<string, AbacResolutionRequest> abacResolutionRequests) throws(1: common.SystemException err),

  /**
   * set a teams attributes
   *  this defines the attribute schema for this team
   *
   * teamId: a valid team id of an active team
   * attributes: the list of attributes to update
   * behaviour: specify how we should handle merging attributes with existing attributes
   */
  list<AbacAttribute> updateTeamAttributes(1: common.UUID teamId, 2: list<AbacAttribute> attributes, 3: AbacUploadBehaviour behaviour) throws(1: common.SystemException err),

  /**
   * retrieve a teams full list of active attributes 
   */
  list<AbacAttribute> getTeamAttributes(1: common.UUID teamId) throws(1: common.SystemException err),

  /**
   * retrieve a teams full list of active attributes
   * deprecated version of getTeamAttributes, for backwards compatibility
   */
  list<AbacAttribute> getAttributes(1: common.UUID teamId) throws(1: common.SystemException err),

  /**
   * set a team's policies 
   */
  list<AbacPolicy> updateTeamPolicies(1: common.UUID teamId, 2: list<AbacPolicy> policies, 3: AbacUploadBehaviour behaviour) throws(1: common.SystemException err),

  /**
   * retrieve a teams full list of active policies
   * teamId: a valid team id of an active team
   * attributes: the list of policies to update
   * behaviour: specify how we should handle merging policies with existing policies 
   */
  list<AbacPolicy> getTeamPolicies(1: common.UUID teamId) throws(1: common.SystemException err),
}
```

I run this: 

`sbt 'scrooge-generator/runMain com.twitter.scrooge.Main -d /Users/brianyeh/scalathrift -s abac.thrift`

I get this: 

```
[error] com.twitter.scrooge.frontend.FileParseException: Exception parsing: /Users/brianyeh/go/src/github.com/parsable/thrift-api/api-def/abac.thrift
[error] Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: /Users/brianyeh/go/src/github.com/parsable/thrift-api/api-def/abac.thrift
[error] Caused by: com.twitter.scrooge.frontend.ParseException: [69.1] failure: string matching regex `[A-Za-z_][A-Za-z0-9_]*' expected but `}' found
[error] 
[error] }
[error] 
[error] ^
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at sbt.Run$.executeTrapExit(Run.scala:124)
[error]         at sbt.Run.run(Run.scala:77)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1150)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1145)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (scrooge-generator / Compile / runMain) Nonzero exit code: 1
[error] Total time: 18 s, completed Apr 30, 2019, 5:53:16 PM
```

linter hits the same issue. The standard code gen with thrift works.

**Comment by ryanoneill** [comment]
Hi @yehbrianyeh, I'm going to try to look into this today.

**Comment by ryanoneill** [comment]
Hi @yehbrianyeh, this is due to the `/**` style comments within structs and enums. Scrooge doesn't seem to like them. If you change those to generic comments then it will work. I believe also moving the ones that are at the end of the line to a separate line before the item will work also.

**Comment by ryanoneill** [comment]
I'm going to close this issue since the question was answered and there was no follow up. Please feel free to open another issue if this wasn't addressed.
