### ISSUE TITLE
Fully Qualified Type Names are not supported in struct/service defs

### ISSUE THREAD

**Issue by hbs** [twitter/scrooge#44]
We have a best practice of using fully qualified names when referencing a Thrift struct in another Thrift IDL, this practice is not supported by the Scrooge generator which therefore is not backward compatible with the standard Thrift compiler.

The standard Thrift compiler accepts the file name (minus the '.thrift' suffix) as a prefix for the structures used in another file, Scrooge doesn't :-( 

file: foo.bar.thrift.data.thrift

namespace java foo.bar.thrift.data

struct A {
  1: bool bool_field,
}

file: foo.var.thrift.services.thrift

namespace java foo.bar.thrift.services

include "foo.bar.thrift.data.thrift"

service Svc {
  list &lt; foo.bar.thrift.data.A &gt; get(1:string name)
}

Calling thrift --gen java:beans foo.bar.thrift.services.thrift correctly generates code when
scrooge -l java foo.bar.thrift.services.thrift (or foo.bar.thrift.*.thrift) produces the following error:

Exception in thread "main" com.twitter.scrooge.TypeNotFoundException: foo.bar.thrift.data.A
	at com.twitter.scrooge.TypeResolver$$anon$1.createMissingEntityException(TypeResolver.scala:74)
	at com.twitter.scrooge.EntityResolver.apply(TypeResolver.scala:60)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:274)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:201)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:204)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:197)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:185)
	at com.twitter.scrooge.TypeResolver$$anonfun$7.apply(TypeResolver.scala:171)
	at com.twitter.scrooge.TypeResolver$$anonfun$7.apply(TypeResolver.scala:171)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
	at scala.collection.immutable.List.map(List.scala:76)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:171)
	at com.twitter.scrooge.TypeResolver$$anonfun$apply$3.apply(TypeResolver.scala:130)
	at com.twitter.scrooge.TypeResolver$$anonfun$apply$3.apply(TypeResolver.scala:129)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at com.twitter.scrooge.TypeResolver.apply(TypeResolver.scala:129)
	at com.twitter.scrooge.Compiler$$anonfun$run$2.apply(Compiler.scala:67)
	at com.twitter.scrooge.Compiler$$anonfun$run$2.apply(Compiler.scala:61)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:30)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
	at com.twitter.scrooge.Compiler.run(Compiler.scala:61)
	at com.twitter.scrooge.Main$.main(Main.scala:98)
	at com.twitter.scrooge.Main.main(Main.scala)

**Comment by mosesn** [comment]
I think this works now.  This test seems to show it working: https://github.com/twitter/scrooge/blob/develop/scrooge-generator-tests/src/test/thrift/scala/inheritance/ddd.thrift

**Comment by hbs** [comment]
The name of the file in the test you referred does not contain dots except for the one before the extension, so I'm not sure it fixes this issue.

**Comment by mosesn** [comment]
Hmm, I thought the issue before was that scrooge didn't handle imports correctly.  I'll try this out locally.

**Comment by mosesn** [comment]
Yep, you're right, it still doesn't work.  Doesn't seem like it'll be too much trouble to implement though, we'll only need to wrap all filenames / fully qualified names in backticks.

**Comment by chenzhuoyu** [comment]
Any updates on this? I seem to have the exact same problem ....
