### ISSUE TITLE
Error when generating thrift files contains Union

### ISSUE THREAD

**Issue by DiveInto** [twitter/scrooge#96]
if I include a union type in thrift file, the generating process fails:

```
[error] Exception in thread "main" com.twitter.scrooge.ParseException: [13.1] failure: string matching regex `\z' expected but `u' found
[error]
[error] union union_value{
[error]
[error] ^
[error] 	at com.twitter.scrooge.ScroogeParser.parse(ScroogeParser.scala:227)
[error] 	at com.twitter.scrooge.ScroogeParser.parseFile(ScroogeParser.scala:235)
[error] 	at com.twitter.scrooge.Main$$anonfun$main$2.apply(Main.scala:92)
[error] 	at com.twitter.scrooge.Main$$anonfun$main$2.apply(Main.scala:88)
[error] 	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
[error] 	at scala.collection.immutable.List.foreach(List.scala:45)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:30)
[error] 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:42)
[error] 	at com.twitter.scrooge.Main$.main(Main.scala:88)
[error] 	at com.twitter.scrooge.Main.main(Main.scala)
```

below is the versions I choose in my project(you can see it [here](https://github.com/DiveInto/thrift-server)):
```
sbt version : 0.11.2
scala version : 2.9.2
scrooge plugin: addSbtPlugin("com.twitter" %% "sbt11-scrooge" % "3.0.0")
scrooge runtime: "com.twitter" %% "scrooge-runtime" % "3.1.0"
```

after several attempts, seems that above is the latest scrooge version I can choose.

any advice? Thanks

**Comment by mosesn** [comment]
We now support unions: https://github.com/twitter/scrooge/blob/develop/scrooge-generator-tests/src/test/thrift/standalone/union.thrift
